version: '3.8'

volumes:
  redis-data:
    driver: local

services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
    - redis-data:/data

  web:
    build: .
    environment:
      REDIS_ADDRESS: 'redis:6379'
    ports:
      - '8080:8080'
    depends_on:
      - redis
